# Even Fibonacci Numbers
# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10
# terms will be:
# 1,2, 3, 5, 8, 13, 21, 34, 55, 89, ..
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued
# terms.


def sum_of_even_fibonacci_numbers():
    # Initialize the first two terms of the Fibonacci sequence
    a,b = 1,2

    # Initialize the sum of even-valued terms
    even_sum = 0

    while a<=4000000:
        # check if the current term (a) is even
        if a % 2 == 0:
            even_sum += a

        # Generate the next term in the sequence
        a, b = b, a+b
        print(a,b)
    print(even_sum)

# Call the function
sum_of_even_fibonacci_numbers()